/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.1
</auto-generated>
------------------------------------------------------------------------------ */

using CsvHelper;
using UserImportUtility.Mvc.Models;
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Telerik.Sitefinity.Abstractions;
using Telerik.Sitefinity.Data;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using Telerik.Sitefinity.Security;
using Telerik.Sitefinity.Security.Model;

namespace UserImportUtility.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "UserImport_MVC", Title = "UserImport", SectionName = "CustomWidgets")]
	public class UserImportController : Controller, IPersonalizable
	{
		// GET: UserImport
		public ActionResult Index()
		{
			var model = new UserImportModel();
			model.Message = this.Message;
			return View(model);
		}

		[HttpPost]
		public ActionResult UploadUsers(UserImportModel model)
		{
			if (model != null && model.FileUpload != null)
			{
				var userImport = new UserImport();
				var success = userImport.ImportUsers(model.FileUpload.InputStream);

			}
			return View(model);
		}



		protected override void HandleUnknownAction(string actionName)
		{
			this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
		}

		public string Message { get; set; }
	}
}