/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.1
</auto-generated>
------------------------------------------------------------------------------ */

using System.Web;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace UserImportUtility.Mvc.Models
{
	public class UserImportModel
	{
		public string Message { get; set; }
		public HttpPostedFileBase FileUpload { get; set; }
	}
}